title: Attila RÃ©tfalvi
logo: /assets/images/me-rounded.png
description: >
  "I break things so users don't have to."

  link: [LinkedIn profilom](https://www.linkedin.com/in/retfalviattila)
show downloads: true
theme: jekyll-theme-minimal
