title: Attila RÃ©tfalvi
logo: /assets/images/me-rounded.png
description: >
  <br>
  I break things so users don't have to.<br><br>
  ğŸ“ Budapest metropolitan area, Hungary<br><br>
  ğŸ“ +36 30 123 4567<br><br>
  âœ‰ï¸ retfalvi.attila[kukac]gmail.com<br><br>

  <a href="https://www.linkedin.com/in/attila-retfalvi/" target="_blank">My LinkedIn profile</a>
show_downloads: true
theme: jekyll-theme-minimal
